"""Context helpers for Source File refresh-generated evidence.

Keeps refresh/enrichment evidence writes from immediately re-dirtying the same
subject while preserving normal dirty marking outside the active refresh scope.
"""

from __future__ import annotations

from contextlib import contextmanager
from contextvars import ContextVar
from typing import Iterator

_ACTIVE_REFRESH_SUBJECT_KEYS: ContextVar[frozenset[str]] = ContextVar("bnl_active_source_refresh_subject_keys", default=frozenset())


def source_refresh_subject_key(value: str) -> str:
    """Return the stable Source File refresh subject key without importing queue code."""

    import re

    return re.sub(r"[^a-z0-9]+", "-", (value or "").strip().lower()).strip("-") or "unknown-subject"


def active_refresh_subject_keys() -> frozenset[str]:
    """Return subject keys currently being refreshed in this context."""

    return _ACTIVE_REFRESH_SUBJECT_KEYS.get()


def is_refresh_generation_subject(subject_name_or_key: str) -> bool:
    """True when evidence for this subject is being generated by its own refresh."""

    return source_refresh_subject_key(subject_name_or_key) in active_refresh_subject_keys()


@contextmanager
def refresh_generation_context(subject_name_or_key: str) -> Iterator[None]:
    """Mark a subject as actively generating Source File refresh evidence."""

    skey = source_refresh_subject_key(subject_name_or_key)
    current = set(active_refresh_subject_keys())
    current.add(skey)
    token = _ACTIVE_REFRESH_SUBJECT_KEYS.set(frozenset(current))
    try:
        yield
    finally:
        _ACTIVE_REFRESH_SUBJECT_KEYS.reset(token)
